### ISSUE TITLE
D9 build fails to call `composer build-assets`

### ISSUE THREAD

**Issue by aaronbauman** [kporras07/tbt-ci-integrations#29] opened 2024-04-12 16:53 UTC
As a result, the pantheon site ends up with an incomplete build.

Makes me feel like I missed something in the project setup... is there a different composer project I should have used for creating the pantheon project?

**Comment by kporras07** [comment] 2024-06-05 22:24
Hi @aaronbauman I would like to understand a bit more your need here.

The way that d9 is setup for Build Tools is using Integrated Composer so there is by default no need for a build-assets script to run. We still add a fake build-assets to composer.json (https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/3.x/src/Commands/ProjectCreateCommand.php#L163) and it's called during site creation but then it's not called for each build.

I'm assuming it's that you're using it to build some other assets (maybe frontend or similar?) and you expect them to be pushed to Pantheon site, does that make sense/somehow matches your use case?

Additional question about your PR; you're replacing `build:gitignore:cut` with `build-assets`; is there any reason in your use case to not have both? I'm inclined to modify your PR and have it call both

**Comment by aaronbauman** [comment] 2024-06-05 22:31
I see, that makes sense.

I'm using d9 build tools the "old way", where the build is done in a CI environment (in my case github actions), rather than using Pantheon's IC.

> you're replacing build:gitignore:cut with build-assets; is there any reason in your use case to not have both?

`build-assets` invokes `\DrupalProject\composer\ScriptHandler::prepareForPantheon`, which in turn does the gitignore-cut operation, so there's no need for both.

**Comment by kporras07** [comment] 2024-06-05 22:35
Yeah, the problem is that the default d9 created site contains an empty build-asset so we can't really commit that :/ 

I think `prepareForPantheon` is coming from d8 template, in d9 we start from the same platform upstream (https://github.com/pantheon-upstreams/drupal-composer-managed) and perform some changes including adding the empty `build-asset` composer script.

I could commit adding `build-assets` without removing `build:gitignore:cut`; would that be enough for your use case?

**Comment by aaronbauman** [comment] 2024-06-06 12:57
Yeah, i imagine that would probably take care of it, thanks

**Comment by kporras07** [comment] 2024-06-06 14:01
I merged the PR. Thanks for your contribution and the discussion here.

**Closed as completed by kporras07** 2024-06-06 14:01 UTC
